import {getOne,putOne} from '../db.js';
import {$,$$,now,toast,goLegacy,openAdd} from './core.js';

let sheet=null,longTimer=null,gesture=null,suppressClickUntil=0;
function openSemantic(){window.dispatchEvent(new CustomEvent('smartlink:v7-open',{detail:{page:'semantic'}}))}
function openMore(){if(sheet){sheet.remove();sheet=null;return}sheet=document.createElement('div');sheet.className='v7-mobile-sheet-backdrop';sheet.innerHTML=`<div class="v7-mobile-sheet"><div class="v7-sheet-handle"></div><button data-v7-mobile-page="read"><i class="ph ph-book-open-text"></i><span>Read Later</span></button><button data-v7-mobile-page="duplicates"><i class="ph ph-copy"></i><span>Duplicates</span></button><button data-v7-mobile-page="archive"><i class="ph ph-archive"></i><span>Archive Lab</span></button><button data-v7-mobile-page="status"><i class="ph ph-pulse"></i><span>System Status</span></button><button data-v7-mobile-page="settings"><i class="ph ph-gear-six"></i><span>Settings</span></button></div>`;document.body.appendChild(sheet);sheet.onclick=e=>{if(e.target===sheet){sheet.remove();sheet=null;return}const p=e.target.closest('[data-v7-mobile-page]')?.dataset.v7MobilePage;if(!p)return;sheet.remove();sheet=null;if(p==='read')document.querySelector('[data-v6-page="read-later"]')?.click();else if(p==='settings')goLegacy('settings');else window.dispatchEvent(new CustomEvent('smartlink:v7-open',{detail:{page:p}}))}}
function injectBottomNav(){if($('#v7-mobile-nav'))return;const el=document.createElement('nav');el.id='v7-mobile-nav';el.className='v7-mobile-nav';el.setAttribute('aria-label','Mobile navigation');el.innerHTML=`<button data-v7-mobile="home"><i class="ph-fill ph-house"></i><span>Home</span></button><button data-v7-mobile="library"><i class="ph ph-squares-four"></i><span>Library</span></button><button class="add" data-v7-mobile="add" aria-label="Add link"><i class="ph ph-plus"></i></button><button data-v7-mobile="ai"><i class="ph ph-brain"></i><span>AI</span></button><button data-v7-mobile="more"><i class="ph ph-dots-three"></i><span>More</span></button>`;document.body.appendChild(el);el.onclick=e=>{const v=e.target.closest('[data-v7-mobile]')?.dataset.v7Mobile;if(!v)return;if(v==='home')goLegacy('home');else if(v==='library')goLegacy('search');else if(v==='add')openAdd();else if(v==='ai')openSemantic();else openMore()}}
function linkIdFromCard(card){return card?.dataset?.id||card?.dataset?.linkId||card?.getAttribute('data-link-id')||card?.querySelector('[data-id]')?.dataset?.id||''}
async function favorite(id){const l=await getOne('links',id);if(!l)return;l.favorite=!l.favorite;l.updatedAt=now();await putOne('links',l);toast(l.favorite?'Added to Favorites':'Removed from Favorites',{kind:'success'});window.dispatchEvent(new Event('hashchange'))}
async function readLater(id){const l=await getOne('links',id);if(!l)return;l.readingState=l.readingState?'':'unread';l.readingUpdatedAt=l.updatedAt=now();await putOne('links',l);toast(l.readingState?'Added to Read Later':'Removed from Read Later',{kind:'success'});window.dispatchEvent(new Event('hashchange'))}
function longSelect(card){const checkbox=card.querySelector('.v6-select');if(checkbox){checkbox.click();navigator.vibrate?.(18);return}card.classList.toggle('v7-long-selected');navigator.vibrate?.(18)}
function bindGestures(){document.addEventListener('pointerdown',e=>{if(matchMedia('(min-width:768px)').matches||e.pointerType==='mouse'||e.target.closest('button,a,input,select,textarea'))return;const card=e.target.closest('.link-card');if(!card)return;gesture={card,id:linkIdFromCard(card),x:e.clientX,y:e.clientY,at:now(),pointerId:e.pointerId};clearTimeout(longTimer);longTimer=setTimeout(()=>{if(gesture?.card===card){longSelect(card);gesture.long=true;suppressClickUntil=now()+700}},560)},{passive:true,capture:true});document.addEventListener('pointermove',e=>{if(!gesture||gesture.pointerId!==e.pointerId)return;if(Math.abs(e.clientX-gesture.x)>14||Math.abs(e.clientY-gesture.y)>14)clearTimeout(longTimer)},{passive:true,capture:true});document.addEventListener('pointerup',e=>{if(!gesture||gesture.pointerId!==e.pointerId)return;clearTimeout(longTimer);const g=gesture;gesture=null;if(g.long||!g.id)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dx)<75||Math.abs(dx)<Math.abs(dy)*1.3)return;suppressClickUntil=now()+650;if(dx>0)favorite(g.id);else readLater(g.id)},{passive:true,capture:true});document.addEventListener('click',e=>{if(now()<suppressClickUntil&&e.target.closest('.link-card')){e.preventDefault();e.stopImmediatePropagation()}},true)}
function lazyCards(){const root=$('#dynamic-content');if(!root)return;new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1){n.querySelectorAll?.('.link-card img').forEach(img=>{img.loading='lazy';img.decoding='async'});if(n.matches?.('.link-card'))n.querySelectorAll('img').forEach(img=>{img.loading='lazy';img.decoding='async'})}}).observe(root,{childList:true,subtree:true})}
export function initMobile(){injectBottomNav();bindGestures();lazyCards();window.addEventListener('resize',()=>{if(innerWidth>=768&&sheet){sheet.remove();sheet=null}},{passive:true})}
