const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'}});
const validUrl=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u:null}catch{return null}};
const meta=(html,name)=>{const re=new RegExp(`<meta[^>]+(?:property|name)=["']${name.replace(':','\\:')}["'][^>]+content=["']([^"']*)["']|<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${name.replace(':','\\:')}["']`,'i');return (html.match(re)||[]).slice(1).find(Boolean)||''};
const titleOf=html=>meta(html,'og:title')||meta(html,'twitter:title')||((html.match(/<title[^>]*>([^<]*)<\/title>/i)||[])[1]||'').trim();
const descOf=html=>meta(html,'og:description')||meta(html,'twitter:description')||meta(html,'description');
const imageOf=html=>meta(html,'og:image')||meta(html,'twitter:image');
const abs=(v,b)=>{try{return new URL(v,b).href}catch{return ''}};
function heuristic(url,title,description){const text=`${url} ${title} ${description}`.toLowerCase();const rs={AI:['ai','chatgpt','openai','claude','gemini','llm'],Development:['github','code','developer','api','programming'],Design:['figma','canva','design','ui','ux'],Media:['youtube','video','music','stream'],Travel:['travel','hotel','flight','booking'],Finance:['stock','finance','invest','trading','crypto'],Learning:['learn','course','education','tutorial','docs'],Shopping:['shop','store','product','amazon','shopee']};let category='General',score=0;for(const [c,ks]of Object.entries(rs)){const n=ks.filter(k=>text.includes(k)).length;if(n>score){score=n;category=c}}return {category,tags:[category],summary:(description||`${category} website or online service.`).slice(0,170)}}
async function fetchPage(url,method='GET'){return fetch(url,{method,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 SmartLinkHub/3.0','accept':'text/html,application/xhtml+xml'}})}
export default {async fetch(req,env){if(req.method==='OPTIONS')return json({ok:true});const u=new URL(req.url),target=validUrl(u.searchParams.get('url'));try{if(u.pathname==='/api/metadata'){if(!target)return json({error:'invalid url'},400);const r=await fetchPage(target);const html=(await r.text()).slice(0,750000),domain=target.hostname.replace(/^www\./,'');return json({title:titleOf(html)||domain,description:descOf(html).slice(0,220),imageUrl:abs(imageOf(html),target),favicon:`https://www.google.com/s2/favicons?sz=96&domain=${encodeURIComponent(domain)}`,domain,status:r.status,finalUrl:r.url})}if(u.pathname==='/api/health'){if(!target)return json({error:'invalid url'},400);let r;try{r=await fetchPage(target,'HEAD');if(r.status===405)r=await fetchPage(target,'GET')}catch(e){return json({status:null,ok:false,state:'broken',error:e.message,checkedAt:Date.now()})}return json({status:r.status,ok:r.ok,state:r.redirected?'redirect':r.ok?'ok':'broken',finalUrl:r.url,checkedAt:Date.now()})}if(u.pathname==='/api/snapshot'){if(!target)return json({error:'invalid url'},400);const r=await fetchPage(target),html=(await r.text()).slice(0,250000);const text=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,4000);return json({type:'html-excerpt',title:titleOf(html)||target.hostname,url:target.href,description:descOf(html).slice(0,220),imageUrl:abs(imageOf(html),target),excerpt:text,capturedAt:Date.now(),status:r.status})}if(u.pathname==='/api/ai'&&req.method==='POST'){const b=await req.json(),fallback=heuristic(b.url||'',b.title||'',b.description||'');if(!env.AI)return json(fallback);try{const prompt=`Classify this website. Return strict JSON with category (short), tags (2-5 short strings), summary (1 concise sentence, max 150 chars). URL: ${b.url}\nTitle: ${b.title}\nDescription: ${b.description}`;const out=await env.AI.run('@cf/meta/llama-3.1-8b-instruct-fast',{prompt,max_tokens:160});const text=out.response||'';const match=text.match(/\{[\s\S]*\}/);return json(match?JSON.parse(match[0]):fallback)}catch{return json(fallback)}}return json({name:'Smart Link Hub API',version:3,endpoints:['/api/metadata','/api/health','/api/snapshot','/api/ai']})}catch(e){return json({error:e.message},500)}}};