-- Smart Link Hub V6: preserve cloud revisions before destructive overwrite.
-- Production migration: smartlink_cloud_state_history_v2

create schema if not exists smartlink_private;

create table if not exists public.smartlink_cloud_state_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.smartlink_login_profiles(id) on delete cascade,
  revision bigint not null,
  state jsonb not null,
  archived_at timestamptz not null default now(),
  unique(profile_id, revision)
);

create index if not exists smartlink_cloud_state_history_profile_revision_idx
  on public.smartlink_cloud_state_history(profile_id, revision desc);

alter table public.smartlink_cloud_state_history enable row level security;
revoke all on table public.smartlink_cloud_state_history from anon, authenticated;

create or replace function smartlink_private.archive_cloud_state_before_change()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  insert into public.smartlink_cloud_state_history(profile_id, revision, state, archived_at)
  values(old.profile_id, old.revision, old.state, now())
  on conflict(profile_id, revision) do nothing;
  return old;
end;
$function$;

drop trigger if exists smartlink_archive_cloud_state_before_change on public.smartlink_cloud_state;
create trigger smartlink_archive_cloud_state_before_change
before update or delete on public.smartlink_cloud_state
for each row execute function smartlink_private.archive_cloud_state_before_change();

-- Seed the pre-history current snapshot so the first V6 upgrade has a recovery point.
insert into public.smartlink_cloud_state_history(profile_id, revision, state, archived_at)
select profile_id, revision, state, updated_at
from public.smartlink_cloud_state
on conflict(profile_id, revision) do nothing;
