-- Smart Link Hub V6: optimistic cloud revisions, restore history, device sessions and login audit.
-- Requires the existing custom SmartLink login/session/cloud tables.

alter table public.smartlink_login_sessions add column if not exists device_name text;

create table if not exists public.smartlink_login_audit (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.smartlink_login_profiles(id) on delete cascade,
  username_key text not null,
  success boolean not null,
  device_name text,
  created_at timestamptz not null default now()
);
alter table public.smartlink_login_audit enable row level security;
revoke all on table public.smartlink_login_audit from anon, authenticated;

create or replace function public.smartlink_login_v2(p_username text, p_pin text, p_device_name text default null)
returns table(profile_id uuid, display_name text, session_token text, expires_at timestamptz, error_code text)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_key text := lower(btrim(coalesce(p_username, '')));
  v_profile public.smartlink_login_profiles%rowtype;
  v_token text;
  v_expires timestamptz;
  v_attempts integer;
  v_device text := left(nullif(btrim(coalesce(p_device_name,'')),''),120);
begin
  select * into v_profile from public.smartlink_login_profiles p where p.username_key=v_key for update;

  if v_profile.id is null or v_key <> 'mek' or p_pin !~ '^[0-9]{6}$' then
    insert into public.smartlink_login_audit(profile_id,username_key,success,device_name)
    values(v_profile.id,left(v_key,80),false,v_device);
    return query select null::uuid,null::text,null::text,null::timestamptz,'invalid_credentials'::text;
    return;
  end if;

  if v_profile.locked_until is not null and v_profile.locked_until > now() then
    insert into public.smartlink_login_audit(profile_id,username_key,success,device_name)
    values(v_profile.id,v_key,false,v_device);
    return query select null::uuid,null::text,null::text,v_profile.locked_until,'try_later'::text;
    return;
  end if;

  if extensions.crypt(p_pin,v_profile.pin_hash) <> v_profile.pin_hash then
    v_attempts := v_profile.failed_attempts + 1;
    update public.smartlink_login_profiles
       set failed_attempts=case when v_attempts>=5 then 0 else v_attempts end,
           locked_until=case when v_attempts>=5 then now()+interval '10 minutes' else null end,
           updated_at=now()
     where id=v_profile.id;
    insert into public.smartlink_login_audit(profile_id,username_key,success,device_name)
    values(v_profile.id,v_key,false,v_device);
    return query select null::uuid,null::text,null::text,null::timestamptz,'invalid_credentials'::text;
    return;
  end if;

  v_token := encode(extensions.gen_random_bytes(32),'hex');
  v_expires := now()+interval '90 days';
  insert into public.smartlink_login_sessions(profile_id,token_hash,expires_at,device_name)
  values(v_profile.id,extensions.digest(v_token,'sha256'),v_expires,v_device);

  delete from public.smartlink_login_sessions s
   where s.profile_id=v_profile.id and (s.expires_at<=now() or s.created_at<now()-interval '90 days');

  update public.smartlink_login_profiles
     set failed_attempts=0,locked_until=null,last_signed_in_at=now(),updated_at=now()
   where id=v_profile.id;
  insert into public.smartlink_login_audit(profile_id,username_key,success,device_name)
  values(v_profile.id,v_key,true,v_device);
  return query select v_profile.id,v_profile.display_name,v_token,v_expires,null::text;
end;
$function$;

create or replace function public.smartlink_state_put_v2(p_token text,p_state jsonb,p_expected_revision bigint default 0)
returns table(revision bigint,updated_at timestamptz,conflict boolean)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_revision bigint;
  v_updated timestamptz;
begin
  if p_state is null or jsonb_typeof(p_state)<>'object' then
    raise exception 'invalid_state' using errcode='22023';
  end if;

  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256')
     and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  update public.smartlink_login_sessions set last_seen_at=now()
   where token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256');

  select c.revision,c.updated_at into v_revision,v_updated
    from public.smartlink_cloud_state c
   where c.profile_id=v_profile_id
   for update;

  if v_revision is null then
    if coalesce(p_expected_revision,0)<>0 then
      return query select 0::bigint,null::timestamptz,true;
      return;
    end if;
    insert into public.smartlink_cloud_state(profile_id,state,revision,updated_at)
    values(v_profile_id,p_state,1,now());
  else
    if v_revision<>coalesce(p_expected_revision,0) then
      return query select v_revision,v_updated,true;
      return;
    end if;
    update public.smartlink_cloud_state
       set state=p_state,revision=revision+1,updated_at=now()
     where profile_id=v_profile_id;
  end if;

  return query
  select c.revision,c.updated_at,false
    from public.smartlink_cloud_state c
   where c.profile_id=v_profile_id;
end;
$function$;

create or replace function public.smartlink_state_versions(p_token text,p_limit integer default 20)
returns table(revision bigint,archived_at timestamptz,links_count integer,collections_count integer,is_current boolean)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_limit integer:=greatest(1,least(coalesce(p_limit,20),50));
begin
  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256')
     and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  update public.smartlink_login_sessions set last_seen_at=now()
   where token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256');

  return query
  select x.revision,x.at,
         case when jsonb_typeof(x.state->'links')='array' then jsonb_array_length(x.state->'links') else 0 end,
         case when jsonb_typeof(x.state->'collections')='array' then jsonb_array_length(x.state->'collections') else 0 end,
         x.current
    from (
      select c.revision,c.updated_at as at,c.state,true as current
        from public.smartlink_cloud_state c where c.profile_id=v_profile_id
      union all
      select h.revision,h.archived_at as at,h.state,false as current
        from public.smartlink_cloud_state_history h where h.profile_id=v_profile_id
    ) x
   order by x.revision desc
   limit v_limit;
end;
$function$;

create or replace function public.smartlink_state_restore(p_token text,p_revision bigint)
returns table(revision bigint,updated_at timestamptz)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_state jsonb;
begin
  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256')
     and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  select h.state into v_state
    from public.smartlink_cloud_state_history h
   where h.profile_id=v_profile_id and h.revision=p_revision
   order by h.id desc limit 1;
  if v_state is null then
    select c.state into v_state from public.smartlink_cloud_state c
     where c.profile_id=v_profile_id and c.revision=p_revision;
  end if;
  if v_state is null then raise exception 'revision_not_found' using errcode='22023'; end if;

  update public.smartlink_cloud_state
     set state=v_state,revision=revision+1,updated_at=now()
   where profile_id=v_profile_id;

  return query select c.revision,c.updated_at
    from public.smartlink_cloud_state c where c.profile_id=v_profile_id;
end;
$function$;

create or replace function public.smartlink_devices(p_token text)
returns table(session_id uuid,device_name text,created_at timestamptz,last_seen_at timestamptz,expires_at timestamptz,is_current boolean)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_hash bytea:=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256');
begin
  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=v_hash and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  return query
  select s.id,coalesce(s.device_name,'Unknown device'),s.created_at,s.last_seen_at,s.expires_at,(s.token_hash=v_hash)
    from public.smartlink_login_sessions s
   where s.profile_id=v_profile_id and s.expires_at>now()
   order by s.last_seen_at desc nulls last,s.created_at desc;
end;
$function$;

create or replace function public.smartlink_device_logout(p_token text,p_session_id uuid)
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_count integer;
begin
  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256')
     and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  delete from public.smartlink_login_sessions s
   where s.id=p_session_id and s.profile_id=v_profile_id;
  get diagnostics v_count=row_count;
  return v_count>0;
end;
$function$;

create or replace function public.smartlink_logout_others(p_token text)
returns integer
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_hash bytea:=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256');
  v_count integer;
begin
  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=v_hash and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  delete from public.smartlink_login_sessions s
   where s.profile_id=v_profile_id and s.token_hash<>v_hash;
  get diagnostics v_count=row_count;
  return v_count;
end;
$function$;

create or replace function public.smartlink_login_history(p_token text,p_limit integer default 20)
returns table(success boolean,device_name text,created_at timestamptz)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_profile_id uuid;
  v_limit integer:=greatest(1,least(coalesce(p_limit,20),50));
begin
  select s.profile_id into v_profile_id
    from public.smartlink_login_sessions s
   where s.token_hash=extensions.digest(convert_to(coalesce(p_token,''),'UTF8'),'sha256')
     and s.expires_at>now()
   limit 1;
  if v_profile_id is null then raise exception 'invalid_session' using errcode='28000'; end if;

  return query
  select a.success,coalesce(a.device_name,'Unknown device'),a.created_at
    from public.smartlink_login_audit a
   where a.profile_id=v_profile_id
   order by a.created_at desc
   limit v_limit;
end;
$function$;

create or replace function smartlink_private.prune_cloud_history()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  delete from public.smartlink_cloud_state_history h
   where h.profile_id=new.profile_id
     and h.id not in (
       select h2.id
         from public.smartlink_cloud_state_history h2
        where h2.profile_id=new.profile_id
        order by h2.revision desc,h2.id desc
        limit 50
     );
  return new;
end;
$function$;

drop trigger if exists smartlink_prune_cloud_history on public.smartlink_cloud_state_history;
create trigger smartlink_prune_cloud_history
after insert on public.smartlink_cloud_state_history
for each row execute function smartlink_private.prune_cloud_history();

alter table public.smartlink_login_profiles enable row level security;
alter table public.smartlink_login_sessions enable row level security;
alter table public.smartlink_cloud_state enable row level security;
alter table public.smartlink_cloud_state_history enable row level security;

-- Remove implicit PUBLIC execution, then grant only the browser RPC surface to anon.
revoke all on function public.smartlink_login(text,text) from public;
revoke all on function public.smartlink_logout(text) from public;
revoke all on function public.smartlink_session(text) from public;
revoke all on function public.smartlink_state_get(text) from public;
revoke all on function public.smartlink_state_put(text,jsonb) from public;
revoke all on function public.smartlink_login_v2(text,text,text) from public;
revoke all on function public.smartlink_state_put_v2(text,jsonb,bigint) from public;
revoke all on function public.smartlink_state_versions(text,integer) from public;
revoke all on function public.smartlink_state_restore(text,bigint) from public;
revoke all on function public.smartlink_devices(text) from public;
revoke all on function public.smartlink_device_logout(text,uuid) from public;
revoke all on function public.smartlink_logout_others(text) from public;
revoke all on function public.smartlink_login_history(text,integer) from public;

grant execute on function public.smartlink_login(text,text) to anon;
grant execute on function public.smartlink_logout(text) to anon;
grant execute on function public.smartlink_session(text) to anon;
grant execute on function public.smartlink_state_get(text) to anon;
grant execute on function public.smartlink_state_put(text,jsonb) to anon;
grant execute on function public.smartlink_login_v2(text,text,text) to anon;
grant execute on function public.smartlink_state_put_v2(text,jsonb,bigint) to anon;
grant execute on function public.smartlink_state_versions(text,integer) to anon;
grant execute on function public.smartlink_state_restore(text,bigint) to anon;
grant execute on function public.smartlink_devices(text) to anon;
grant execute on function public.smartlink_device_logout(text,uuid) to anon;
grant execute on function public.smartlink_logout_others(text) to anon;
grant execute on function public.smartlink_login_history(text,integer) to anon;
